version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  tests: true

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dupword
    - errcheck
    - errorlint
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - intrange
    - misspell
    - modernize
    - nakedret
    - nilerr
    - noctx
    - perfsprint
    - predeclared
    - recvcheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
