version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  tests: true

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - errname
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gochecknoinits
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - godoclint
    - gomoddirectives
    - goprintffuncname
    - gosmopolitan
    - govet
    - iface
    - ineffassign
    - intrange
    - iotamixing
    - makezero
    - mirror
    - misspell
    - modernize
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - predeclared
    - prealloc
    - reassign
    - recvcheck
    - spancheck
    - staticcheck
    - tagalign
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
